version: '3.8'

services:
  mini-waf:
    image: ghcr.io/lyx9527/mini-waf:master
    container_name: mini-waf
    ports:
      - "49888:48080" # WAF 服务端口
      - "49777:8081"   # 管理控制台端口
    environment:
      # 替换为真实的 MySQL 比如外部或者如下面启动的 mysql 容器
      - DATABASE_URL=mysql://mini_waf_user:password@mysql:3306/mini_waf
      - JWT_SECRET=super_secret_waf_key_please_change
      - RUST_LOG=info
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mini-waf-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mini_waf
      - MYSQL_USER=mini_waf_user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mini_waf_user", "-ppassword" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mysql_data:
