use axum::Json;
use serde::Deserialize;

const NGINX_CONF_DIR: &str = "/etc/nginx/conf.d";
const NGINX_CONTAINER_NAME: &str = "mini-waf-nginx";
/// 主配置暂存在共享卷中，由 exec 复制到 /etc/nginx/nginx.conf
const NGINX_MAIN_CONF_STAGING: &str = "/etc/nginx/conf.d/.nginx_main.conf";

// ─── 请求结构体 ────────────────────────────────────────

#[derive(Deserialize)]
pub struct NginxConfigRequest {
    pub listen_port: u16,
    pub server_name: Option<String>,
    pub root_path: Option<String>,
    #[serde(default)]
    pub raw_content: Option<String>,
}

#[derive(Deserialize)]
pub struct EditNginxConfigRequest {
    pub old_listen_port: u16,
    pub listen_port: u16,
    pub server_name: Option<String>,
    pub root_path: Option<String>,
    #[serde(default)]
    pub raw_content: Option<String>,
}

#[derive(Deserialize)]
pub struct DeleteNginxConfigRequest {
    pub listen_port: u16,
}

#[derive(Deserialize)]
pub struct MainConfRequest {
    pub content: String,
}

// ─── 工具函数 ──────────────────────────────────────────

/// 校验 server_name / root_path 不包含注入字符
/// server_name 只允许字母、数字、点、连字符、下划线、通配符 *
fn validate_server_name(s: &str) -> bool {
    s.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_' | '*'))
}

/// 校验 root_path 只允许绝对路径中的合法字符（不能含分号、花括号等注入符）
fn validate_path(s: &str) -> bool {
    s.starts_with('/')
        && s.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '/' | '-' | '_' | '.' | '~'))
}

/// 生成 nginx server block 配置内容 (基础模式)
fn generate_server_block(port: u16, server_name: Option<&str>, root: &str) -> String {
    let sn = server_name.unwrap_or("_");
    format!(
        r#"# Auto-generated by MINI-WAF — port {}
server {{
    listen {};
    server_name {};
    root {};
    index index.html index.htm;

    location / {{
        try_files $uri $uri/ /index.html;
    }}
}}
"#,
        port, port, sn, root,
    )
}

fn conf_filename(port: u16) -> String {
    format!("waf_site_{}.conf", port)
}

/// 通过 Docker Socket 在 nginx 容器内执行命令
async fn docker_exec(cmd: Vec<&str>) -> Result<Vec<u8>, String> {
    use tokio::net::UnixStream;
    use tokio::io::{AsyncWriteExt, AsyncReadExt};

    let socket_path = "/var/run/docker.sock";

    // Step 1: 创建 exec 实例（Connection: close 确保响应完成后 Docker 关闭连接）
    let create_body = serde_json::json!({
        "AttachStdout": true,
        "AttachStderr": true,
        "Cmd": cmd
    });
    let body_str = create_body.to_string();
    let create_request = format!(
        "POST /containers/{}/exec HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\nContent-Type: application/json\r\nContent-Length: {}\r\n\r\n{}",
        NGINX_CONTAINER_NAME, body_str.len(), body_str
    );

    let mut stream = UnixStream::connect(socket_path).await.map_err(|e| {
        format!("无法连接 Docker Socket: {}。请确保已挂载 /var/run/docker.sock", e)
    })?;
    stream.write_all(create_request.as_bytes()).await.map_err(|e| format!("写入 Docker Socket 失败: {}", e))?;
    // 半关闭写端，通知 Docker 我们发完了（某些实现需要此步骤）
    stream.shutdown().await.ok();

    let mut buf = vec![0u8; 8192];
    let n = stream.read(&mut buf).await.map_err(|e| format!("读取 Docker 响应失败: {}", e))?;
    let resp = String::from_utf8_lossy(&buf[..n]);

    let exec_id = if let Some(id_start) = resp.find("\"Id\":\"") {
        let start = id_start + 6;
        if let Some(id_end) = resp[start..].find('"') {
            resp[start..start + id_end].to_string()
        } else {
            return Err("无法解析 exec ID".to_string());
        }
    } else {
        return Err(format!("创建 exec 失败: {}", resp));
    };

    // Step 2: 执行并读取输出
    // Connection: close 强制 Docker 在命令完成后关闭 Socket，loop 才能收到 EOF
    let start_body = serde_json::json!({"Detach": false, "Tty": false});
    let start_str = start_body.to_string();
    let start_request = format!(
        "POST /exec/{}/start HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\nContent-Type: application/json\r\nContent-Length: {}\r\n\r\n{}",
        exec_id, start_str.len(), start_str
    );

    let mut stream2 = UnixStream::connect(socket_path).await.map_err(|e| format!("连接失败: {}", e))?;
    stream2.write_all(start_request.as_bytes()).await.map_err(|e| format!("执行失败: {}", e))?;
    // 半关闭写端，让 Docker 知道请求已发送完毕
    stream2.shutdown().await.ok();

    let mut result = Vec::new();
    let mut tmp = vec![0u8; 8192];
    loop {
        match stream2.read(&mut tmp).await {
            Ok(0) => break, // Docker 关闭了连接 (Connection: close 保证)
            Ok(n) => result.extend_from_slice(&tmp[..n]),
            Err(e) => return Err(format!("读取结果失败: {}", e)),
        }
    }

    Ok(result)
}

/// 与 docker_exec 相同，但可指定任意容器名（供其他模块复用）
pub async fn docker_exec_in(container: &str, cmd: Vec<&str>) -> Result<Vec<u8>, String> {
    use tokio::net::UnixStream;
    use tokio::io::{AsyncWriteExt, AsyncReadExt};

    let socket_path = "/var/run/docker.sock";

    let create_body = serde_json::json!({
        "AttachStdout": true,
        "AttachStderr": true,
        "Cmd": cmd
    });
    let body_str = create_body.to_string();
    let create_request = format!(
        "POST /containers/{}/exec HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\nContent-Type: application/json\r\nContent-Length: {}\r\n\r\n{}",
        container, body_str.len(), body_str
    );

    let mut stream = UnixStream::connect(socket_path).await
        .map_err(|e| format!("无法连接 Docker Socket: {}", e))?;
    stream.write_all(create_request.as_bytes()).await
        .map_err(|e| format!("写入失败: {}", e))?;
    stream.shutdown().await.ok();

    let mut buf = vec![0u8; 8192];
    let n = stream.read(&mut buf).await
        .map_err(|e| format!("读取响应失败: {}", e))?;
    let resp = String::from_utf8_lossy(&buf[..n]);

    let exec_id = if let Some(id_start) = resp.find("\"Id\":\"") {
        let start = id_start + 6;
        if let Some(id_end) = resp[start..].find('"') {
            resp[start..start + id_end].to_string()
        } else {
            return Err("无法解析 exec ID".to_string());
        }
    } else {
        return Err(format!("容器 {} exec 创建失败: {}", container, resp));
    };

    let start_body = serde_json::json!({"Detach": false, "Tty": false});
    let start_str = start_body.to_string();
    let start_request = format!(
        "POST /exec/{}/start HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\nContent-Type: application/json\r\nContent-Length: {}\r\n\r\n{}",
        exec_id, start_str.len(), start_str
    );

    let mut stream2 = UnixStream::connect(socket_path).await
        .map_err(|e| format!("连接失败: {}", e))?;
    stream2.write_all(start_request.as_bytes()).await
        .map_err(|e| format!("执行失败: {}", e))?;
    stream2.shutdown().await.ok();

    let mut result = Vec::new();
    let mut tmp = vec![0u8; 8192];
    loop {
        match stream2.read(&mut tmp).await {
            Ok(0) => break,
            Ok(n) => result.extend_from_slice(&tmp[..n]),
            Err(e) => return Err(format!("读取结果失败: {}", e)),
        }
    }
    Ok(result)
}

/// Reload nginx
async fn reload_nginx() -> Result<String, String> {
    let resp = docker_exec(vec!["nginx", "-s", "reload"]).await?;
    let output = extract_exec_body(&resp);
    let _ = output; // reload 无需检查输出
    Ok("nginx reload 成功".to_string())
}

/// Test nginx config
async fn test_nginx_config() -> Result<String, String> {
    let resp = docker_exec(vec!["nginx", "-t"]).await?;
    let output = extract_exec_body(&resp);
    if output.contains("successful") || output.contains("ok") {
        Ok("配置测试通过".to_string())
    } else {
        Err(format!("配置测试失败: {}", output))
    }
}

// ─── API: 站点配置 CRUD ───────────────────────────────

/// GET /api/v1/nginx/configs — 列出所有 nginx 配置
pub async fn list_nginx_configs() -> Json<serde_json::Value> {
    let conf_dir = std::path::Path::new(NGINX_CONF_DIR);
    let mut configs = Vec::new();

    if let Ok(entries) = std::fs::read_dir(conf_dir) {
        for entry in entries.flatten() {
            let filename = entry.file_name().to_string_lossy().to_string();
            if filename.starts_with("waf_site_") && filename.ends_with(".conf") {
                if let Ok(content) = std::fs::read_to_string(entry.path()) {
                    // 修复逻辑炸弹1: 以空格或分号分割，只取第一个词，兼容
                    // "listen 80;", "listen 443 ssl;", "listen 80 default_server;"
                    let port = content.lines()
                        .find(|l| l.trim().starts_with("listen"))
                        .and_then(|l| l.trim().strip_prefix("listen "))
                        .and_then(|rest| rest.split(|c| c == ' ' || c == ';').next())
                        .and_then(|s| s.trim().parse::<u16>().ok())
                        .unwrap_or(0);

                    let server_name = content.lines()
                        .find(|l| l.trim().starts_with("server_name"))
                        .and_then(|l| l.trim().strip_prefix("server_name "))
                        .and_then(|rest| rest.split(|c| c == ' ' || c == ';').next())
                        .map(|s| s.trim().to_string())
                        .filter(|s| s != "_" && !s.is_empty());

                    let root = content.lines()
                        .find(|l| l.trim().starts_with("root"))
                        .and_then(|l| l.trim().strip_prefix("root "))
                        .and_then(|rest| rest.split(';').next())
                        .map(|s| s.trim().to_string())
                        .unwrap_or_default();

                    configs.push(serde_json::json!({
                        "listen_port": port,
                        "server_name": server_name,
                        "root_path": root,
                        "filename": filename,
                        "raw_content": content,
                    }));
                }
            }
        }
    }

    configs.sort_by_key(|c| c["listen_port"].as_u64().unwrap_or(0));
    Json(serde_json::json!({ "configs": configs }))
}

/// POST /api/v1/nginx/configs — 新增
pub async fn add_nginx_config(
    Json(payload): Json<NginxConfigRequest>,
) -> Json<serde_json::Value> {
    // 注入防护: 校验 server_name 和 root_path
    if let Some(sn) = &payload.server_name {
        if !sn.is_empty() && !validate_server_name(sn) {
            return Json(serde_json::json!({
                "status": "error",
                "message": "server_name 包含非法字符，只允许字母、数字、点、连字符、下划线、通配符 *"
            }));
        }
    }
    if let Some(root) = &payload.root_path {
        if !root.is_empty() && !validate_path(root) {
            return Json(serde_json::json!({
                "status": "error",
                "message": "root_path 必须是以 / 开头的合法路径"
            }));
        }
    }

    let conf_path = std::path::Path::new(NGINX_CONF_DIR).join(conf_filename(payload.listen_port));

    if conf_path.exists() {
        return Json(serde_json::json!({
            "status": "error",
            "message": format!("端口 {} 的配置已存在", payload.listen_port)
        }));
    }

    let content = if let Some(raw) = &payload.raw_content {
        raw.clone()
    } else {
        generate_server_block(
            payload.listen_port,
            payload.server_name.as_deref(),
            payload.root_path.as_deref().unwrap_or("/usr/share/nginx/html"),
        )
    };

    if let Err(e) = std::fs::write(&conf_path, &content) {
        return Json(serde_json::json!({ "status": "error", "message": format!("写入失败: {}", e) }));
    }

    let reload_msg = match reload_nginx().await {
        Ok(msg) => msg,
        Err(e) => return Json(serde_json::json!({ "status": "warning", "message": format!("配置已保存，但 reload 失败: {}", e) })),
    };

    Json(serde_json::json!({ "status": "success", "message": format!("端口 {} 配置已创建。{}", payload.listen_port, reload_msg) }))
}

/// PUT /api/v1/nginx/configs — 编辑
pub async fn edit_nginx_config(
    Json(payload): Json<EditNginxConfigRequest>,
) -> Json<serde_json::Value> {
    let old_path = std::path::Path::new(NGINX_CONF_DIR).join(conf_filename(payload.old_listen_port));
    if old_path.exists() {
        let _ = std::fs::remove_file(&old_path);
    }

    let new_path = std::path::Path::new(NGINX_CONF_DIR).join(conf_filename(payload.listen_port));

    let content = if let Some(raw) = &payload.raw_content {
        raw.clone()
    } else {
        generate_server_block(
            payload.listen_port,
            payload.server_name.as_deref(),
            payload.root_path.as_deref().unwrap_or("/usr/share/nginx/html"),
        )
    };

    if let Err(e) = std::fs::write(&new_path, &content) {
        return Json(serde_json::json!({ "status": "error", "message": format!("写入失败: {}", e) }));
    }

    let reload_msg = match reload_nginx().await {
        Ok(msg) => msg,
        Err(e) => return Json(serde_json::json!({ "status": "warning", "message": format!("已保存，reload 失败: {}", e) })),
    };

    Json(serde_json::json!({ "status": "success", "message": format!("端口 {} 配置已更新。{}", payload.listen_port, reload_msg) }))
}

/// DELETE /api/v1/nginx/configs — 删除
pub async fn delete_nginx_config(
    Json(payload): Json<DeleteNginxConfigRequest>,
) -> Json<serde_json::Value> {
    let conf_path = std::path::Path::new(NGINX_CONF_DIR).join(conf_filename(payload.listen_port));
    if !conf_path.exists() {
        return Json(serde_json::json!({ "status": "error", "message": format!("端口 {} 配置不存在", payload.listen_port) }));
    }
    if let Err(e) = std::fs::remove_file(&conf_path) {
        return Json(serde_json::json!({ "status": "error", "message": format!("删除失败: {}", e) }));
    }

    let reload_msg = match reload_nginx().await {
        Ok(msg) => msg,
        Err(e) => return Json(serde_json::json!({ "status": "warning", "message": format!("已删除，reload 失败: {}", e) })),
    };

    Json(serde_json::json!({ "status": "success", "message": format!("端口 {} 配置已删除。{}", payload.listen_port, reload_msg) }))
}

// ─── API: 主配置文件 ──────────────────────────────────

/// 默认 nginx.conf 模板（当 staging 文件不存在时使用）
fn default_nginx_conf() -> &'static str {
    r#"user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    include /etc/nginx/conf.d/*.conf;
}
"#
}

/// 判断 staging 文件内容是否有效（非 HTTP 响应头、非空、包含 nginx 关键字）
fn is_valid_nginx_conf(content: &str) -> bool {
    let trimmed = content.trim();
    !trimmed.is_empty()
        && !trimmed.starts_with("HTTP/")
        && !trimmed.starts_with("Content-")
        && (trimmed.contains("worker_processes")
            || trimmed.contains("events")
            || trimmed.contains("http")
            || trimmed.contains("server"))
}

/// GET /api/v1/nginx/main-conf — 读取主配置文件
/// 策略: staging 文件（有效时）> 默认模板
/// 注: 不通过 docker exec 读取，避免 multiplexed stream 解析问题
pub async fn get_main_conf() -> Json<serde_json::Value> {
    let staging = std::path::Path::new(NGINX_MAIN_CONF_STAGING);

    if staging.exists() {
        if let Ok(content) = std::fs::read_to_string(staging) {
            if is_valid_nginx_conf(&content) {
                return Json(serde_json::json!({ "content": content }));
            } else {
                // staging 内容损坏（如存了 HTTP 响应头），删除并重建
                eprintln!(
                    "[WARN] staging 文件内容无效，已重置: {}",
                    content.chars().take(80).collect::<String>()
                );
                let _ = std::fs::remove_file(staging);
            }
        }
    }

    // staging 不存在或已损坏：返回内置默认模板，并写入 staging 供后续使用
    let default_conf = default_nginx_conf().to_string();
    let _ = std::fs::write(staging, &default_conf);
    Json(serde_json::json!({ "content": default_conf }))
}

/// PUT /api/v1/nginx/main-conf — 保存主配置文件（原子化更新）
/// 顺序: 写 staging → 用 staging 测试 → 测试通过后才覆盖 nginx.conf → reload
pub async fn save_main_conf(
    Json(payload): Json<MainConfRequest>,
) -> Json<serde_json::Value> {
    // 1. 写入 staging 文件（共享卷中，nginx 容器可直接访问）
    if let Err(e) = std::fs::write(NGINX_MAIN_CONF_STAGING, &payload.content) {
        return Json(serde_json::json!({ "status": "error", "message": format!("写入 staging 失败: {}", e) }));
    }

    // 2. 先测试 staging 文件的配置（关键：此时 nginx.conf 仍是旧的安全版本）
    let test_raw = match docker_exec(vec!["nginx", "-t", "-c", "/etc/nginx/conf.d/.nginx_main.conf"]).await {
        Ok(b) => b,
        Err(e) => return Json(serde_json::json!({ "status": "error", "message": format!("测试配置失败: {}", e) })),
    };
    let test_output = extract_exec_body(&test_raw);
    // nginx -t 成功时输出包含 "successful"，失败时包含错误信息（到 stderr）
    if !test_output.contains("successful") && !test_output.is_empty() {
        // 测试失败：nginx.conf 未被修改，依然安全
        return Json(serde_json::json!({
            "status": "error",
            "message": format!("配置语法错误，已拦截，nginx.conf 未被修改:\n{}", test_output)
        }));
    }

    // 3. 测试通过：正式覆盖 nginx.conf（原子化关键步骤）
    if let Err(e) = docker_exec(vec!["cp", "/etc/nginx/conf.d/.nginx_main.conf", "/etc/nginx/nginx.conf"]).await {
        return Json(serde_json::json!({ "status": "error", "message": format!("覆写 nginx.conf 失败: {}", e) }));
    }

    // 4. Reload（配置已经测试通过，reload 不会失败）
    let reload_msg = match reload_nginx().await {
        Ok(msg) => msg,
        Err(e) => return Json(serde_json::json!({ "status": "warning", "message": format!("已保存，reload 失败: {}", e) })),
    };

    Json(serde_json::json!({ "status": "success", "message": format!("主配置已更新。{}", reload_msg) }))
}

/// POST /api/v1/nginx/test — 测试当前配置
pub async fn test_config() -> Json<serde_json::Value> {
    match test_nginx_config().await {
        Ok(msg) => Json(serde_json::json!({ "status": "success", "message": msg })),
        Err(e) => Json(serde_json::json!({ "status": "error", "message": e })),
    }
}

/// 按 Docker Multiplexed Stream 协议解析 exec 输出
/// 协议格式: [stream_type(1B)] [padding(3B)] [size(4B big-endian)] [payload(size B)] ...
fn extract_exec_body(raw: &[u8]) -> String {
    // Step1: 跳过 HTTP 响应头（找到 \r\n\r\n）
    let body_start = raw.windows(4)
        .position(|w| w == b"\r\n\r\n")
        .map(|p| p + 4)
        .unwrap_or(0);
    let mut body = &raw[body_start..];

    // Step2: 检测是否是 chunked transfer encoding
    // 判断: 响应头中是否含 "Transfer-Encoding: chunked"
    let header_section = &raw[..body_start.saturating_sub(4)];
    let is_chunked = header_section
        .windows(b"Transfer-Encoding: chunked".len())
        .any(|w| w.eq_ignore_ascii_case(b"Transfer-Encoding: chunked"));

    // Step3: 如果 chunked，解码所有 chunk（可能有多个）
    let decoded: Vec<u8>;
    if is_chunked {
        let mut out = Vec::new();
        let mut pos = 0;
        while pos < body.len() {
            // 读取 chunk size 行（hex 数字后跟 \r\n）
            if let Some(crlf) = body[pos..].windows(2).position(|w| w == b"\r\n") {
                let size_str = std::str::from_utf8(&body[pos..pos + crlf]).unwrap_or("");
                let chunk_size = usize::from_str_radix(size_str.trim(), 16).unwrap_or(0);
                pos += crlf + 2; // 跳过 size 行和 \r\n
                if chunk_size == 0 {
                    break; // 末尾 chunk
                }
                if pos + chunk_size <= body.len() {
                    out.extend_from_slice(&body[pos..pos + chunk_size]);
                    pos += chunk_size + 2; // 跳过 chunk data 和尾随 \r\n
                } else {
                    out.extend_from_slice(&body[pos..]);
                    break;
                }
            } else {
                break;
            }
        }
        decoded = out;
        body = &decoded;
    }

    // Step4: 解析 Docker multiplexed stream frames
    let mut result = Vec::new();
    let mut i = 0;
    while i + 8 <= body.len() {
        let stream_type = body[i];
        let size = u32::from_be_bytes([body[i+4], body[i+5], body[i+6], body[i+7]]) as usize;
        i += 8;
        let end = (i + size).min(body.len());
        if stream_type == 1 || stream_type == 2 {
            // stdout(1) 或 stderr(2) 都收集
            result.extend_from_slice(&body[i..end]);
        }
        i = end;
    }

    String::from_utf8_lossy(&result).trim().to_string()
}
