use axum::Json;
use serde::Deserialize;

const NGINX_CONF_DIR: &str = "/etc/nginx/conf.d";
const NGINX_CONTAINER_NAME: &str = "mini-waf-nginx";
/// 主配置暂存在共享卷中，由 exec 复制到 /etc/nginx/nginx.conf
const NGINX_MAIN_CONF_STAGING: &str = "/etc/nginx/conf.d/.nginx_main.conf";

// ─── 请求结构体 ────────────────────────────────────────

#[derive(Deserialize)]
pub struct NginxConfigRequest {
    pub listen_port: u16,
    pub server_name: Option<String>,
    pub root_path: Option<String>,
    #[serde(default)]
    pub raw_content: Option<String>,
}

#[derive(Deserialize)]
pub struct EditNginxConfigRequest {
    pub old_listen_port: u16,
    pub listen_port: u16,
    pub server_name: Option<String>,
    pub root_path: Option<String>,
    #[serde(default)]
    pub raw_content: Option<String>,
}

#[derive(Deserialize)]
pub struct DeleteNginxConfigRequest {
    pub listen_port: u16,
}

#[derive(Deserialize)]
pub struct MainConfRequest {
    pub content: String,
}

// ─── 工具函数 ──────────────────────────────────────────

/// 生成 nginx server block 配置内容 (基础模式)
fn generate_server_block(port: u16, server_name: Option<&str>, root: &str) -> String {
    let sn = server_name.unwrap_or("_");
    format!(
        r#"# Auto-generated by MINI-WAF — port {}
server {{
    listen {};
    server_name {};
    root {};
    index index.html index.htm;

    location / {{
        try_files $uri $uri/ /index.html;
    }}
}}
"#,
        port, port, sn, root,
    )
}

fn conf_filename(port: u16) -> String {
    format!("waf_site_{}.conf", port)
}

/// 通过 Docker Socket 在 nginx 容器内执行命令
async fn docker_exec(cmd: Vec<&str>) -> Result<Vec<u8>, String> {
    use tokio::net::UnixStream;
    use tokio::io::{AsyncWriteExt, AsyncReadExt};

    let socket_path = "/var/run/docker.sock";

    // Step 1: 创建 exec 实例
    let create_body = serde_json::json!({
        "AttachStdout": true,
        "AttachStderr": true,
        "Cmd": cmd
    });
    let body_str = create_body.to_string();
    let create_request = format!(
        "POST /containers/{}/exec HTTP/1.1\r\nHost: localhost\r\nContent-Type: application/json\r\nContent-Length: {}\r\n\r\n{}",
        NGINX_CONTAINER_NAME, body_str.len(), body_str
    );

    let mut stream = UnixStream::connect(socket_path).await.map_err(|e| {
        format!("无法连接 Docker Socket: {}。请确保已挂载 /var/run/docker.sock", e)
    })?;
    stream.write_all(create_request.as_bytes()).await.map_err(|e| format!("写入 Docker Socket 失败: {}", e))?;

    let mut buf = vec![0u8; 8192];
    let n = stream.read(&mut buf).await.map_err(|e| format!("读取 Docker 响应失败: {}", e))?;
    let resp = String::from_utf8_lossy(&buf[..n]);

    let exec_id = if let Some(id_start) = resp.find("\"Id\":\"") {
        let start = id_start + 6;
        if let Some(id_end) = resp[start..].find('"') {
            resp[start..start + id_end].to_string()
        } else {
            return Err("无法解析 exec ID".to_string());
        }
    } else {
        return Err(format!("创建 exec 失败: {}", resp));
    };

    // Step 2: 执行并读取输出（循环读直到 EOF）
    let start_body = serde_json::json!({"Detach": false, "Tty": false});
    let start_str = start_body.to_string();
    let start_request = format!(
        "POST /exec/{}/start HTTP/1.1\r\nHost: localhost\r\nContent-Type: application/json\r\nContent-Length: {}\r\n\r\n{}",
        exec_id, start_str.len(), start_str
    );

    let mut stream2 = UnixStream::connect(socket_path).await.map_err(|e| format!("连接失败: {}", e))?;
    stream2.write_all(start_request.as_bytes()).await.map_err(|e| format!("执行失败: {}", e))?;

    let mut result = Vec::new();
    let mut tmp = vec![0u8; 8192];
    loop {
        match stream2.read(&mut tmp).await {
            Ok(0) => break, // EOF
            Ok(n) => result.extend_from_slice(&tmp[..n]),
            Err(e) => return Err(format!("读取结果失败: {}", e)),
        }
    }

    Ok(result)
}

/// Reload nginx
async fn reload_nginx() -> Result<String, String> {
    let resp = docker_exec(vec!["nginx", "-s", "reload"]).await?;
    let output = extract_exec_body(&resp);
    let _ = output; // reload 无需检查输出
    Ok("nginx reload 成功".to_string())
}

/// Test nginx config
async fn test_nginx_config() -> Result<String, String> {
    let resp = docker_exec(vec!["nginx", "-t"]).await?;
    let output = extract_exec_body(&resp);
    if output.contains("successful") || output.contains("ok") {
        Ok("配置测试通过".to_string())
    } else {
        Err(format!("配置测试失败: {}", output))
    }
}

// ─── API: 站点配置 CRUD ───────────────────────────────

/// GET /api/v1/nginx/configs — 列出所有 nginx 配置
pub async fn list_nginx_configs() -> Json<serde_json::Value> {
    let conf_dir = std::path::Path::new(NGINX_CONF_DIR);
    let mut configs = Vec::new();

    if let Ok(entries) = std::fs::read_dir(conf_dir) {
        for entry in entries.flatten() {
            let filename = entry.file_name().to_string_lossy().to_string();
            if filename.starts_with("waf_site_") && filename.ends_with(".conf") {
                if let Ok(content) = std::fs::read_to_string(entry.path()) {
                    let port = content.lines()
                        .find(|l| l.trim().starts_with("listen"))
                        .and_then(|l| l.trim().strip_prefix("listen "))
                        .and_then(|l| l.trim_end_matches(';').trim().parse::<u16>().ok())
                        .unwrap_or(0);

                    let server_name = content.lines()
                        .find(|l| l.trim().starts_with("server_name"))
                        .and_then(|l| l.trim().strip_prefix("server_name "))
                        .map(|l| l.trim_end_matches(';').trim().to_string())
                        .filter(|s| s != "_");

                    let root = content.lines()
                        .find(|l| l.trim().starts_with("root"))
                        .and_then(|l| l.trim().strip_prefix("root "))
                        .map(|l| l.trim_end_matches(';').trim().to_string())
                        .unwrap_or_default();

                    configs.push(serde_json::json!({
                        "listen_port": port,
                        "server_name": server_name,
                        "root_path": root,
                        "filename": filename,
                        "raw_content": content,
                    }));
                }
            }
        }
    }

    configs.sort_by_key(|c| c["listen_port"].as_u64().unwrap_or(0));
    Json(serde_json::json!({ "configs": configs }))
}

/// POST /api/v1/nginx/configs — 新增
pub async fn add_nginx_config(
    Json(payload): Json<NginxConfigRequest>,
) -> Json<serde_json::Value> {
    let conf_path = std::path::Path::new(NGINX_CONF_DIR).join(conf_filename(payload.listen_port));

    if conf_path.exists() {
        return Json(serde_json::json!({
            "status": "error",
            "message": format!("端口 {} 的配置已存在", payload.listen_port)
        }));
    }

    let content = if let Some(raw) = &payload.raw_content {
        raw.clone()
    } else {
        generate_server_block(
            payload.listen_port,
            payload.server_name.as_deref(),
            payload.root_path.as_deref().unwrap_or("/usr/share/nginx/html"),
        )
    };

    if let Err(e) = std::fs::write(&conf_path, &content) {
        return Json(serde_json::json!({ "status": "error", "message": format!("写入失败: {}", e) }));
    }

    let reload_msg = match reload_nginx().await {
        Ok(msg) => msg,
        Err(e) => return Json(serde_json::json!({ "status": "warning", "message": format!("配置已保存，但 reload 失败: {}", e) })),
    };

    Json(serde_json::json!({ "status": "success", "message": format!("端口 {} 配置已创建。{}", payload.listen_port, reload_msg) }))
}

/// PUT /api/v1/nginx/configs — 编辑
pub async fn edit_nginx_config(
    Json(payload): Json<EditNginxConfigRequest>,
) -> Json<serde_json::Value> {
    let old_path = std::path::Path::new(NGINX_CONF_DIR).join(conf_filename(payload.old_listen_port));
    if old_path.exists() {
        let _ = std::fs::remove_file(&old_path);
    }

    let new_path = std::path::Path::new(NGINX_CONF_DIR).join(conf_filename(payload.listen_port));

    let content = if let Some(raw) = &payload.raw_content {
        raw.clone()
    } else {
        generate_server_block(
            payload.listen_port,
            payload.server_name.as_deref(),
            payload.root_path.as_deref().unwrap_or("/usr/share/nginx/html"),
        )
    };

    if let Err(e) = std::fs::write(&new_path, &content) {
        return Json(serde_json::json!({ "status": "error", "message": format!("写入失败: {}", e) }));
    }

    let reload_msg = match reload_nginx().await {
        Ok(msg) => msg,
        Err(e) => return Json(serde_json::json!({ "status": "warning", "message": format!("已保存，reload 失败: {}", e) })),
    };

    Json(serde_json::json!({ "status": "success", "message": format!("端口 {} 配置已更新。{}", payload.listen_port, reload_msg) }))
}

/// DELETE /api/v1/nginx/configs — 删除
pub async fn delete_nginx_config(
    Json(payload): Json<DeleteNginxConfigRequest>,
) -> Json<serde_json::Value> {
    let conf_path = std::path::Path::new(NGINX_CONF_DIR).join(conf_filename(payload.listen_port));
    if !conf_path.exists() {
        return Json(serde_json::json!({ "status": "error", "message": format!("端口 {} 配置不存在", payload.listen_port) }));
    }
    if let Err(e) = std::fs::remove_file(&conf_path) {
        return Json(serde_json::json!({ "status": "error", "message": format!("删除失败: {}", e) }));
    }

    let reload_msg = match reload_nginx().await {
        Ok(msg) => msg,
        Err(e) => return Json(serde_json::json!({ "status": "warning", "message": format!("已删除，reload 失败: {}", e) })),
    };

    Json(serde_json::json!({ "status": "success", "message": format!("端口 {} 配置已删除。{}", payload.listen_port, reload_msg) }))
}

// ─── API: 主配置文件 ──────────────────────────────────

/// GET /api/v1/nginx/main-conf — 读取主配置文件
/// 优先读取共享卷中的 staging 文件，不存在时才通过 docker exec 获取并缓存
pub async fn get_main_conf() -> Json<serde_json::Value> {
    // 优先: 从共享卷 staging 文件读取（最可靠）
    let staging = std::path::Path::new(NGINX_MAIN_CONF_STAGING);
    if staging.exists() {
        if let Ok(content) = std::fs::read_to_string(staging) {
            if !content.is_empty() {
                return Json(serde_json::json!({ "content": content }));
            }
        }
    }

    // 降级: 通过 docker exec 读取 nginx 容器内的原始配置，同时缓存到 staging
    match docker_exec(vec!["cat", "/etc/nginx/nginx.conf"]).await {
        Ok(raw_bytes) => {
            let content = extract_exec_body(&raw_bytes);
            if !content.is_empty() {
                // 缓存到 staging 文件，下次直接读
                let _ = std::fs::write(staging, &content);
                return Json(serde_json::json!({ "content": content }));
            }
            Json(serde_json::json!({ "content": "", "error": "exec 返回空内容" }))
        }
        Err(e) => {
            Json(serde_json::json!({ "content": "", "error": e }))
        }
    }
}

/// PUT /api/v1/nginx/main-conf — 保存主配置文件
pub async fn save_main_conf(
    Json(payload): Json<MainConfRequest>,
) -> Json<serde_json::Value> {
    // 1. 写入 staging 文件（共享卷中）
    if let Err(e) = std::fs::write(NGINX_MAIN_CONF_STAGING, &payload.content) {
        return Json(serde_json::json!({ "status": "error", "message": format!("写入 staging 失败: {}", e) }));
    }

    // 2. 通过 docker exec 复制到 nginx 的真正位置
    match docker_exec(vec!["cp", "/etc/nginx/conf.d/.nginx_main.conf", "/etc/nginx/nginx.conf"]).await {
        Ok(_) => {}
        Err(e) => {
            return Json(serde_json::json!({ "status": "error", "message": format!("复制配置失败: {}", e) }));
        }
    }

    // 3. 测试配置
    match test_nginx_config().await {
        Ok(_) => {},
        Err(e) => {
            return Json(serde_json::json!({ "status": "error", "message": format!("配置测试失败: {}", e) }));
        }
    }

    // 4. Reload
    let reload_msg = match reload_nginx().await {
        Ok(msg) => msg,
        Err(e) => return Json(serde_json::json!({ "status": "warning", "message": format!("已保存，reload 失败: {}", e) })),
    };

    Json(serde_json::json!({ "status": "success", "message": format!("主配置已更新。{}", reload_msg) }))
}

/// POST /api/v1/nginx/test — 测试当前配置
pub async fn test_config() -> Json<serde_json::Value> {
    match test_nginx_config().await {
        Ok(msg) => Json(serde_json::json!({ "status": "success", "message": msg })),
        Err(e) => Json(serde_json::json!({ "status": "error", "message": e })),
    }
}

/// 按 Docker Multiplexed Stream 协议解析 exec 输出
/// 协议格式: [stream_type(1B)] [padding(3B)] [size(4B big-endian)] [payload(size B)] ...
fn extract_exec_body(raw: &[u8]) -> String {
    // 先跳过 HTTP 响应头（找到 \r\n\r\n）
    let body_start = raw.windows(4)
        .position(|w| w == b"\r\n\r\n")
        .map(|p| p + 4)
        .unwrap_or(0);

    let mut body = &raw[body_start..];

    // 如果服务器用 chunked transfer encoding，跳过 chunk size 行
    // chunked 格式: <hex_size>\r\n<data>\r\n
    // 简单检测：第一个字节是否是 hex 字符
    if body.first().map(|b| b.is_ascii_hexdigit()).unwrap_or(false) {
        // 跳过 chunk size 行
        if let Some(end) = body.windows(2).position(|w| w == b"\r\n") {
            body = &body[end + 2..];
        }
    }

    // 解析 Docker multiplexed stream frames
    let mut result = Vec::new();
    let mut i = 0;
    while i + 8 <= body.len() {
        let stream_type = body[i];
        // stream_type: 0=stdin, 1=stdout, 2=stderr
        let size = u32::from_be_bytes([body[i+4], body[i+5], body[i+6], body[i+7]]) as usize;
        i += 8;
        if i + size > body.len() {
            // 数据不完整，取剩余全部
            result.extend_from_slice(&body[i..]);
            break;
        }
        if stream_type == 1 || stream_type == 2 {
            // stdout 或 stderr 都收集
            result.extend_from_slice(&body[i..i+size]);
        }
        i += size;
    }

    String::from_utf8_lossy(&result).trim().to_string()
}
